FEATURES = ['doy', 'dow', 'hasProvidence',
       'lat', 'lon', 'Days_Since_First_Case', 'Days_Since_Ten_Cases',
       'Days_Since_Hundred_Cases', 'Days_Since_First_Fatal',
       'Days_Since_Ten_Fatal', 'Days_Since_Hundred_Fatal', 'Smoking_Rate',
            'Population_final',
#             'tests',
#        'testpop', 'density', 'medianage', 'urbanpop',
#             'quarantine', 'schools',
#        'publicplace',
            #'gatheringlimit', 'gathering', 'nonessential',
       'hospibed', 'smokers', 'sex0', 'sex14', 'sex25', 'sex54', 'sex64',
       'sex65plus', 'sexratio', 'lung', 'femalelung', 'malelung', 'gdp2019',
       'healthexp', 'healthperpop', 'fertility', 
            #'firstcase', 'totalcases',
       #'activecases', 'newcases', 'deaths', 'newdeaths', 'recovered',
       #'critical', 'casediv1m', 'deathdiv1m',
             'CC_7D_1stCase',
 'CC_14D_1stCase',
 'CC_21D_1stCase',
 'CC_28D_1stCase',
 'CC_35D_1stCase',
 'CC_60D_1stCase',
 'F_7D_1stCase',
 'F_14D_1stCase',
 'F_21D_1stCase',
 'F_28D_1stCase',
 'F_35D_1stCase',
 'F_60D_1stCase',
 'CC_7D_10Case',
 'CC_14D_10Case',
 'CC_21D_10Case',
 'CC_28D_10Case',
 'CC_35D_10Case',
 'CC_60D_10Case',
 'F_7D_10Case',
 'F_14D_10Case',
 'F_21D_10Case',
 'F_28D_10Case',
 'F_35D_10Case',
 'F_60D_10Case',
 'CC_7D_1Fatal',
 'CC_14D_1Fatal',
 'CC_21D_1Fatal',
 'CC_28D_1Fatal',
 'CC_35D_1Fatal',
 'CC_60D_1Fatal',
 'F_7D_1Fatal',
 'F_14D_1Fatal',
 'F_21D_1Fatal',
 'F_28D_1Fatal',
 'F_35D_1Fatal',
 'F_60D_1Fatal'
           ]
TARGET = ['ConfirmedCases_Log']
